# mongod.conf
storage:
  dbPath: /data/db
  ## MongoDB 7 默认就是开启的
  # journal:
  #   enabled: true

systemLog:
  destination: console
  logAppend: true
  # path: /var/log/mongodb/mongod.log # 容器内部的路径

net:
  port: 27017
  bindIp: 0.0.0.0   # 允许所有 IP 连接（容器内通常需要这样）

#security:
#  authorization: enabled  # 开启认证